"""empty message

Revision ID: 2fa6ec8e0e4f
Revises: f194a3afaef4
Create Date: 2025-02-24 17:45:29.690314

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2fa6ec8e0e4f'
down_revision = 'f194a3afaef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.Enum('Midterm', 'Final', 'Quiz', 'Assignment', name='exam_types'), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    # ### end Alembic commands ###
